### ISSUE TITLE
error: library glmnet has Fortran sources but no Fortran compiler found

### ISSUE THREAD

**Issue by jeffreysmith-jrs** [earth-chris/elapid#9] opened 2021-04-22 19:21 UTC
I had to install a fortran compiler (windows x64) prior to being able to install glmnet. I followed these directions https://people.eng.unimelb.edu.au/ammoffat/teaching/20005/Install-MinGW.pdf.

**Comment by earth-chris** [comment] 2021-04-30 01:55
Seems like this will best be handled by documenting the issue in a separate `Windows Install` section, or something of the sort. There's no way to do this directly through conda (say, by including it in the `environment.yml` config), is there?

**Comment by jeffreysmith-jrs** [comment] 2021-04-30 02:06
Not that I'm aware of, it does seem like there will have to be something for a windows instillation. Sadly glment doesn't have a conda installation on Windows so you have to build it yourself via pip. I can write something if it helps but in short I just did 

`conda install scikit-learn -c conda-forge -n envName`
`conda install rasterio -c conda-forge -n envName`
`conda activate envName`
`pip install glmnet`
`pip install elapid`

You importantly have to have the fortran compiler running while you pip install glmnet

**Comment by aFewThings** [comment] 2022-08-03 14:12
For the installation of glmnet, I followed @jeffreysmith-jrs solution and got this error. 

This seems to appear due to the unstable compiling of fortran or other reason that could not build glmnet properly.

```
...
running install_scripts
running install_clib
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
customize MSVCCompiler
...
```

But it generated glmnet library. so I have imported built glmnet, and it outputs as below.

```
>>> import glmnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\gicha\Desktop\python-glmnet-2.2.1\glmnet\__init__.py", line 3, in <module>
    from .logistic import LogitNet
  File "C:\Users\gicha\Desktop\python-glmnet-2.2.1\glmnet\logistic.py", line 14, in <module>
    from _glmnet import lognet, splognet, lsolns
ImportError: DLL load failed: The specified module could not be found.
```



I've tried many ways to solve this problem, but the problem is still not solved.
- [installing microsoft build tools 20XX](https://github.com/numpy/numpy/issues/12016#issuecomment-555354320)
- [downgrading python version](https://github.com/numpy/numpy/issues/12016#issuecomment-544953139)
- [other solution](https://github.com/civisanalytics/python-glmnet/issues/67#issuecomment-864912076)

In fact, these issues are related to glmnet, so it is difficult to ask if there is a specific solution.

I just wonder if glmnet is a necessary library to implement maxent.

Because glmnet is installed based on Fortran compiler, it requires a difficult installation procedure significantly for Windows users.

Is there any way to replace LogitNet (from glmnet) of MaxEnt model with the model implemented in scikit-learn? (like LogisticRegression)

**Comment by earth-chris** [comment] 2022-08-04 06:02
hey @aFewThings, thanks for reaching out. I understand that `glmnet` is a pain for windows users and an `sklearn` implementation would probably be best.

`elapid` is built with `glmnet` because it wraps the same fortran library used by the `R` implementation of maxent, and I wanted to maintain fidelity to existing tools. I think the primary value of this implementation is that there are highly customized regularization parameters defined for different feature types that were tuned specifically for maxent.

I don't see an immediate way to pass regularization terms to the `sklearn` model estimator, which would mean all feature types would be uniformly weighted. Maxent increases regularization penalties on hinge and other feature types, meaning they're more likely to be dropped from the model to reduce overfitting. I just see that you can pass a single scalar value for the `C` parameter.

I'm not sure the effect this would have on model predictions. But I suppose this can be easily evaluated empirically to see if the differences are meaningful.

**Comment by aFewThings** [comment] 2022-08-04 16:22
Thanks for your response. 
I would check your suggestion.
Anyway, I finally installed glmnet. So I have commented for someone who wants to install on 64-bit windows. 

https://github.com/civisanalytics/python-glmnet/issues/67#issuecomment-1205459620

**Comment by earth-chris** [comment] 2022-09-08 07:04
ok, i've done some testing and i think there are two ways to try and resolve this.

1. recommend Windows users install [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about), which allows users to run a native linux terminal (and they'd probably just have to run `sudo apt install gfortran` as a pre-req.
2. include a try/except import for `glmnet` and use the sklearn `LogisticRegression()` class in case `glmnet` can't be found.

The latter isn't a great option, but it's viable. The agreement between `sklearn` and `glmnet` models-based models is `r2 = 0.77`. There seems to be little bias; the errors look normally distributed.

The following are notes for me following testing the sklearn approach:

- Regularization is indeed different, and can't be fine tuned feature-by-feature like with `glmnet`. That's just how it is, so 🤷🏻. But a good way to translate from the `beta_multiplier` to a comparable `C` regularization parameter is `C = 2 / (1 - np.exp(-beta_multiplier)))`
- The `.coef_` attribute for LogisticRegression models contains the beta scores that can be used to scale model predictions in the same way that maxent does.

**Comment by earth-chris** [comment] 2022-10-05 07:57
Closing this issue after a couple of developments:

1. `glmnet` is now an optional dependency and can be installed as-needed. This was handled with the sklearn model fitting procedure.
2. there is a `conda` package for elapid now, which should handle some of the common headaches associated with windows installs.
3. added this thread to a new [install guide](https://elapid.org/install/) to reference as necessary.

**Closed as completed by earth-chris** 2022-10-05 07:57 UTC
Labels: bug, documentation
